name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    name: Build - ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - arch: "aarch64_generic"
            sdk: "https://downloads.openwrt.org/releases/24.10.0-rc4/targets/rockchip/armv8/openwrt-sdk-24.10.0-rc4-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
    steps:
      - uses: actions/checkout@v2
      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk zstd\
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 unzip wget \
          python3-distutils python3-setuptools python3-dev rsync subversion \
          swig time xsltproc zlib1g-dev

      - name: Install OpenWrt SDK
        run: |
          # 下载 OpenWrt SDK
          wget -O openwrt-sdk.tar.zst ${{ matrix.target.sdk }}
          # 使用 zstd 解压 .tar.zst 文件
          tar --use-compress-program=zstd -xf openwrt-sdk.tar.zst
          # 移动解压后的目录到指定名称
          mv -f openwrt-sdk-* openwrt-sdk
      - name: Build Package
        run: |
          echo "src-link netbird $GITHUB_WORKSPACE" > openwrt-sdk/feeds.conf
          echo 'CONFIG_PACKAGE_netbird=y
          ' >> openwrt-sdk/.config
          cd openwrt-sdk

          git clone https://github.com/kuoruan/openwrt-upx.git package/upx
          git -C package/upx checkout 2c2ee0d696ea6084bee893a2861a7ed0729728ed # upx version: v2022-10-20

          #cat feeds.conf.default >> feeds.conf
          echo 'src-git packages https://git.openwrt.org/feed/packages.git^c84e022ee9fae5884a7c698746bfac4d74a12a2d' >> feeds.conf 
          cat feeds.conf

          ./scripts/feeds update -a > /dev/null
          rm -rf ./feeds/packages/net/netbird
          make defconfig

          ./scripts/feeds install -d y -f -a
          make package/netbird/compile V=s CONFIG_NETBIRD_COMPRESS_UPX=y
          tree bin/packages/
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: netbird-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/netbird/netbird*.ipk
          if-no-files-found: error
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: openwrt-sdk/bin/packages/*/netbird/netbird*.ipk
          tag: ${{ github.ref }}
